openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3

paths:
  /pet/findByTags:
    get:
      summary: Find pets by tags
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

  /pet:
    post:
      summary: Add a new pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          example: 10
        category:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: Dogs
          required:
            - id
            - name
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
            example: "https://example.com/pet1.jpg"
        tags:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 0
              name:
                type: string
                example: string
        status:
          type: string
          example: available